cmake_minimum_required(VERSION 3.23)
project(Test C)

set(CMAKE_C_STANDARD 23)

add_executable(Test
        old_nn.c
        functions.c
        repository.c
        generator.c
        utils.c
        tests.c
        Iterators/iterator.h
        Iterators/Implementations/full_batch_iterator.c
        Iterators/Implementations/full_batch_iterator.h
        Iterators/Implementations/mini-batch_iterator.c
        Iterators/Implementations/mini-batch_iterator.h
        Iterators/iterator-util.c
        Iterators/iterator-util.h
        learning_rate_sechduler.c
        learning_rate_sechduler.h
        data_selector.c
        data_selector.h
        optimizer.c
        optimizer.h
        old_layer.c
        old_layer.h
        hyper_parameters.c
        hyper_parameters.h
        multi-threading.c
        multi-threading.h
        list.c
        list.h
        yaml.c
        yaml.h
        store.c
        conv_layer.c
        conv_layer.h
        Layers/layer.c
        Layers/layer.h
        Layers/Types/activation_layer.c
        Layers/Types/activation_layer.h
        Layers/Types/dense_layer.c
        Layers/Types/dense_layer.h
        neural_network.c
        neural_network.h
)
add_library(Export SHARED
        export.c
        old_nn.c
        functions.c
        utils.c
        repository.c
        Iterators/iterator.h
        Iterators/Implementations/full_batch_iterator.c
        Iterators/Implementations/full_batch_iterator.h
        Iterators/Implementations/mini-batch_iterator.c
        Iterators/Implementations/mini-batch_iterator.h
        Iterators/iterator-util.c
        Iterators/iterator-util.h
        learning_rate_sechduler.c
        learning_rate_sechduler.h
        data_selector.c
        data_selector.h
        optimizer.c
        optimizer.h
        old_layer.c
        old_layer.h
        hyper_parameters.c
        hyper_parameters.h
        multi-threading.c
        multi-threading.h
        list.c
        list.h
        yaml.c
        yaml.h
        store.c
        Layers/layer.c
        Layers/layer.h
        Layers/Types/activation_layer.c
        Layers/Types/activation_layer.h
        Layers/Types/dense_layer.c
        Layers/Types/dense_layer.h
        neural_network.c
        neural_network.h
)
