<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="libExport.dll" />
      <Content Include="libExport.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Update="mnist-data\t10k-images.idx3-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\t10k-labels.idx1-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\train-images.idx3-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\train-labels.idx1-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
