<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="mnist-data\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Core">
        <HintPath>bin\Debug\net9.0\Core.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="mnist-data\t10k-images.idx3-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\t10k-labels.idx1-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\train-images.idx3-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist-data\train-labels.idx1-ubyte">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
